apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: "./"
    repoURL: https://github.com/skabrits/Microservice-sys.git
    targetRevision: "main"
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"